/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VgrKOuLynZb
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useEffect } from "react";
import { toast } from "sonner";
import { CharacterPanelView as CharacterPanel } from "./CharacterPanel/CharacterPanel";
import { FiltersPanel } from "./FiltersPanel/FiltersPanel";
import {
  useSetCharacterKnown,
  useSetCharacterUnknown,
} from "./FlashcardsContainer.mutations";
import { useFetchChineseCharacter } from "./FlashcardsContainer.queries";
import { useAppState } from "./hooks/useAppState";
import { useOnConfigurationChange } from "./hooks/useOnConfgiurationChange";
import { SessionCharacterLists } from "./session-character-lists";

const useKeyboardShortcuts = ({
  handleCheck,
  handleReveal,
  handleUnknown,
}: {
  handleCheck: () => void;
  handleReveal: () => void;
  handleUnknown: () => void;
}) => {
  useEffect(() => {
    const handleKeyDown = async (event: KeyboardEvent) => {
      switch (event.key) {
        case "ArrowLeft":
          await handleCheck();
          break;
        case "ArrowRight":
          await handleUnknown();
          break;
        case "ArrowUp":
          handleReveal();
          break;
        default:
          break;
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [handleCheck, handleReveal, handleUnknown]);
};

export function FlashcardsContainer() {
  const {
    showIdeogram,
    setShowIdeogram,
    characterType,
    setCharacterType,
    characterImportance,
    setCharacterImportance,
    currentCharacter,
    setCurrentCharacter,
    nextCharacter,
    setNextCharacter,
    seenCharacterIds,
    setSeenCharacterIds,
    knownCharacters,
    setKnownCharacters,
    unknownCharacters,
    setUnknownCharacters,
    addKnownCharacter,
    addUnknownCharacter,
    shiftForward,
  } = useAppState();
  const { handleCharacterUnknown } = useSetCharacterUnknown();
  const { handleCharacterKnown } = useSetCharacterKnown();
  const { fetchCharacter } = useFetchChineseCharacter({
    characterType,
    characterImportance,
  });

  useOnConfigurationChange({
    fetchCharacter,
    characterType,
    characterImportance,
    setShowIdeogram,
    setCurrentCharacter,
    setNextCharacter,
    setSeenCharacterIds,
    setKnownCharacters,
    setUnknownCharacters,
  });

  const prefetchNextCharacter = async () => {
    try {
      const fetched = await fetchCharacter();
      setNextCharacter(fetched);
    } catch (e) {
      toast.error("Failed to fetch next card.");
    }
  };

  const handleCheck = async () => {
    setShowIdeogram(false);
    if (!currentCharacter) {
      console.error("No current character when handling check.");
      return;
    }
    const oldId = currentCharacter.id;
    addKnownCharacter(currentCharacter);
    shiftForward({
      currentCharacter,
      nextCharacter,
    });
    await handleCharacterKnown(oldId);
    await prefetchNextCharacter();
  };
  const handleReveal = () => {
    setShowIdeogram((prevState) => !prevState);
  };
  const handleUnknown = async () => {
    setShowIdeogram(false);
    if (!currentCharacter) {
      console.error("No current character when handling unknown.");
      return;
    }
    const oldId = currentCharacter.id;
    addUnknownCharacter(currentCharacter);
    shiftForward({
      currentCharacter,
      nextCharacter,
    });
    await handleCharacterUnknown(oldId);
    await prefetchNextCharacter();
  };

  useKeyboardShortcuts({
    handleCheck,
    handleReveal,
    handleUnknown,
  });

  const isLoading = currentCharacter === null;
  const uniqueSeenCount = seenCharacterIds.length;

  return (
    <div className="dark flex flex-col items-center justify-center h-screen bg-background text-card-foreground relative overflow-hidden">
      <div className="absolute inset-0 bg-linear-to-br from-blue-950/30 via-background to-indigo-950/20 pointer-events-none" />
      <div className="absolute top-4 right-4 z-10 glass rounded-xl px-4 py-2 text-sm font-medium text-muted-foreground shadow-lg">
        <span className="text-foreground font-semibold">{uniqueSeenCount}</span>{" "}
        seen
      </div>
      <div className="relative flex w-full max-w-7xl gap-6 px-6">
        <FiltersPanel
          setCharacterType={setCharacterType}
          setCharacterImportance={setCharacterImportance}
        />
        <CharacterPanel
          data={currentCharacter ?? null}
          isLoading={isLoading}
          showIdeogram={showIdeogram}
          handleCheck={handleCheck}
          handleReveal={handleReveal}
          handleUnknown={handleUnknown}
          knownCharacters={knownCharacters}
          totalCount={uniqueSeenCount}
        />
        <SessionCharacterLists
          knownCharacters={knownCharacters}
          unknownCharacters={unknownCharacters}
        />
      </div>
    </div>
  );
}
