/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VgrKOuLynZb
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { compact } from "lodash-es";
import { useEffect } from "react";
import { toast } from "sonner";
import { CharacterPanelView as CharacterPanel } from "./CharacterPanel/CharacterPanel";
import { FiltersPanel } from "./FiltersPanel/FiltersPanel";
import {
  useSetCharacterKnown,
  useSetCharacterUnknown,
} from "./FlashcardsContainer.mutations";
import { useFetchChineseCharacter } from "./FlashcardsContainer.queries";
import { useAppState } from "./hooks/useAppState";
import { useOnConfigurationChange } from "./hooks/useOnConfgiurationChange";
import { ChineseCharacter } from "./types";
import { Card } from "./ui/card";

const useKeyboardShortcuts = ({
  handleCheck,
  handleReveal,
  handleUnknown,
  handleBack,
}: {
  handleCheck: () => void;
  handleReveal: () => void;
  handleUnknown: () => void;
  handleBack: () => void;
}) => {
  useEffect(() => {
    const handleKeyDown = async (event: KeyboardEvent) => {
      switch (event.key) {
        case "ArrowLeft":
          await handleCheck();
          break;
        case "ArrowRight":
          await handleUnknown();
          break;
        case "ArrowUp":
          handleReveal();
          break;
        case "Backspace":
          event.preventDefault();
          handleBack();
          break;
        default:
          break;
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [handleCheck, handleReveal, handleUnknown, handleBack]);
};

export function FlashcardsContainer() {
  const {
    showIdeogram,
    setShowIdeogram,
    characterType,
    setCharacterType,
    characterImportance,
    setCharacterImportance,
    previousCharacter,
    setPreviousCharacter,
    currentCharacter,
    setCurrentCharacter,
    nextCharacter,
    setNextCharacter,
    seenCharacterIds,
    setSeenCharacterIds,
    knownCount,
    incrementKnownCount,
    shiftForward,
    shiftBack,
  } = useAppState();
  const { handleCharacterUnknown } = useSetCharacterUnknown();
  const { handleCharacterKnown } = useSetCharacterKnown();
  const { fetchCharacter } = useFetchChineseCharacter({
    characterType,
    characterImportance,
  });

  useOnConfigurationChange({
    fetchCharacter,
    characterType,
    characterImportance,
    setShowIdeogram,
    setPreviousCharacter,
    setCurrentCharacter,
    setNextCharacter,
    setSeenCharacterIds,
  });

  const prefetchNextCharacter = async () => {
    try {
      const fetched = await fetchCharacter();
      setNextCharacter(fetched);
    } catch (e) {
      toast.error("Failed to fetch next card.");
    }
  };

  const handleCheck = async () => {
    setShowIdeogram(false);
    if (!currentCharacter) {
      console.error("No current character when handling check.");
      return;
    }
    const oldId = currentCharacter.id;
    shiftForward({
      currentCharacter,
      nextCharacter,
    });
    incrementKnownCount();
    await handleCharacterKnown(oldId);
    await prefetchNextCharacter();
  };
  const handleReveal = () => {
    setShowIdeogram((prevState) => !prevState);
  };
  const handleUnknown = async () => {
    setShowIdeogram(false);
    if (!currentCharacter) {
      console.error("No current character when handling unknown.");
      return;
    }
    const oldId = currentCharacter.id;
    shiftForward({
      currentCharacter,
      nextCharacter,
    });
    await handleCharacterUnknown(oldId);
    await prefetchNextCharacter();
  };

  const handleBack = () => {
    if (!previousCharacter) {
      console.error("No previous character when handling back.");
      return;
    }
    shiftBack({
      previousCharacter,
      currentCharacter,
    });
  };
  useKeyboardShortcuts({
    handleCheck,
    handleReveal,
    handleUnknown,
    handleBack,
  });

  const isLoading = currentCharacter === null;
  const uniqueSeenCount = seenCharacterIds.length;

  return (
    <div className="dark flex flex-col items-center justify-center h-screen bg-background text-card-foreground">
      <Card className="absolute top-4 right-4 bg-card px-4 py-2 rounded-lg text-sm font-medium">
        {uniqueSeenCount}
      </Card>
      <div className="flex w-full max-w-5xl">
        <FiltersPanel
          setCharacterType={setCharacterType}
          setCharacterImportance={setCharacterImportance}
        />
        <CharacterPanel
          data={currentCharacter ?? null}
          isLoading={isLoading}
          showIdeogram={showIdeogram}
          handleCheck={handleCheck}
          handleReveal={handleReveal}
          handleUnknown={handleUnknown}
          handleBack={handleBack}
          canGoBack={Boolean(previousCharacter)}
          knownCount={knownCount}
          totalCount={uniqueSeenCount}
        />
      </div>
    </div>
  );
}
